### PR TITLE
try open in new window otherwise open in current window

### LINKED ISSUE #369: Auto detect pop-up blocker for Join Meeting button in GroupBar.tsx
Instead of using page sizes (breaking points) which is unreliable, always try to pop up the Tencent meeting page and fall back to opening in the same window if failed. See https://stackoverflow.com/a/2917

### PR DESCRIPTION
**Pull request by ada-only-one-ada**
fixed #369 
When the button is clicked, it should always attempt to open in a new window. If the pop-up window is blocked, then it should open in the current window.

### CODE REVIEW

File: src/components/GroupBar.tsx [hunk 1]
```diff
@@ -60,10 +60,17 @@ export default function GroupBar({
       if (!link) {
         setShowMeetingQuotaWarning(true);
       } else {
-        window.open(link, '_blank');
+        const newWindow = window.open(link, '_blank');
+        if (!newWindow || newWindow.closed || typeof newWindow.closed === 'undefined') {
+          // popup blocked
+          await launchMeetingInSameWindow(groupId);
```
Comment (weihanwang) [inline src/components/GroupBar.tsx:66]: We shouldn't simply call launchMeetingInSameWindow() because calling the same RPC twice is wasteful and overall logic may not be correct. Merge these two functions instead. Note that their logic is similar but they have nuanced differences. Be very careful when change the code here. Make sure you fully understand the logic before making the change.

**Review by weihanwang — CHANGES_REQUESTED** [review]

File: src/components/GroupBar.tsx [hunk 2]
```diff
@@ -53,31 +53,21 @@ export default function GroupBar({
...
       const link = await trpc.meetings.join.mutate({ groupId: groupId });
       if (!link) {
         setShowMeetingQuotaWarning(true);
         setJoining(false);
       } else {
-        window.location.href = link;
-        // Time is needed for the meeting page to load.
-        setTimeout(() => setJoining(false), 5000);
+        const newWindow = window.open(link, '_blank');
+        if (!newWindow || newWindow.closed || typeof newWindow.closed === 'undefined') {
```
Comment (weihanwang) [inline src/components/GroupBar.tsx:65]: link to the reference page where you get this trick. Also add a comment about the intent of this block

File: src/components/GroupBar.tsx [hunk 3]
```diff
@@ -53,31 +53,21 @@ export default function GroupBar({
...
+          window.location.href = link;
+          setTimeout(() => setJoining(false), 5000);
```
Comment (weihanwang) [inline src/components/GroupBar.tsx:67]: do not remove the original comment above this line.

File: src/components/GroupBar.tsx [hunk 4]
```diff
@@ -53,31 +53,21 @@ export default function GroupBar({
...
-      } else {
-        window.open(link, '_blank');
-      }
-    } finally {
-      setJoining(false);
-    }
-  };
-
-  const launchMeetingInSameWindow = async (groupId: string) => {
+  const launchMeeting = async (groupId: string) => {
```
Comment (weihanwang) [inline src/components/GroupBar.tsx:56]: Test on all the following devices using the preview link of this PR to make sure it works as expected:

1. Desktop browsers: Chrome, Edge, Safari, Firefox
2. an iPhone
3. an Android phone

If you don't have all the devices, ask for volunteers who have to help you test.

Comment (ada-only-one-ada) [reply src/components/GroupBar.tsx:56]: ### iPhone Safari 

- **用户设置阻止弹窗时**
  - 自动在当前标签页打开腾讯会议。**Status: Pass**

- **用户设置不阻止弹窗时**
  - 弹出一个 Pop-up 窗口，提示："网站正在打开弹出式窗口"。
    - **用户选择允许：**
      - 在新标签页打开腾讯会议。**Status: Pass**
    - **用户选择阻止：**
      - 底部显示：```糟糕！Load failed```错误。见以下视频。
      - 在当前标签页打开腾讯会议后，底部错误消失。**Status: Unsure**

https://github.com/user-attachments/assets/8380ed85-f7e1-4a57-9bd5-0d94a73c49b2

### iPhone Chrome & iPhone Firefox

- **用户设置阻止弹窗时**
  - 自动在当前标签页打开腾讯会议。**Status: Pass**

- **用户设置不阻止弹窗时**
  - 自动在新标签页打开腾讯会议。**Status: Pass**

### iPhone Edge
- 无论用户是否设置阻止弹窗，都自动在新标签页打开腾讯会议。**Status: Pass**

**Review by weihanwang — APPROVED** [review]
